// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: const String.fromEnvironment('WEB_API_KEY'),
    appId: const String.fromEnvironment('WEB_APP_ID'),
    messagingSenderId: '381990099686',
    projectId: 'carrier-6d7c1',
    authDomain: 'carrier-6d7c1.firebaseapp.com',
    storageBucket: 'carrier-6d7c1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: const String.fromEnvironment('ANDROID_API_KEY'),
    appId: const String.fromEnvironment('ANDROID_APP_ID'),
    messagingSenderId: '381990099686',
    projectId: 'carrier-6d7c1',
    storageBucket: 'carrier-6d7c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: const String.fromEnvironment('IOS_API_KEY'),
    appId: const String.fromEnvironment('IOS_APP_ID'),
    messagingSenderId: '381990099686',
    projectId: 'carrier-6d7c1',
    storageBucket: 'carrier-6d7c1.firebasestorage.app',
    iosBundleId: 'com.example.carrier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: const String.fromEnvironment('MACOS_API_KEY'),
    appId: const String.fromEnvironment('MACOS_APP_ID'),
    messagingSenderId: '381990099686',
    projectId: 'carrier-6d7c1',
    storageBucket: 'carrier-6d7c1.firebasestorage.app',
    iosBundleId: 'com.example.carrier',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: const String.fromEnvironment('WINDOW_API_KEY'),
    appId: const String.fromEnvironment('WINDOW_API_KEY'),
    messagingSenderId: '381990099686',
    projectId: 'carrier-6d7c1',
    authDomain: 'carrier-6d7c1.firebaseapp.com',
    storageBucket: 'carrier-6d7c1.firebasestorage.app',
  );
}
