// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoATrZhVHaXK_pEXJjjxXVpNErJ536aHU',
    appId: '1:381990099686:web:e2c8269c313b3dd6f6f927',
    messagingSenderId: '381990099686',
    projectId: 'carrier-6d7c1',
    authDomain: 'carrier-6d7c1.firebaseapp.com',
    storageBucket: 'carrier-6d7c1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbL2iIdEjUBU_OLefkfIk3uTIaEtUghzM',
    appId: '1:381990099686:android:7d4c95f2039c328af6f927',
    messagingSenderId: '381990099686',
    projectId: 'carrier-6d7c1',
    storageBucket: 'carrier-6d7c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7otd3nTN63ydPyIBR9BmT0jvZ2xkwO6w',
    appId: '1:381990099686:ios:3ed83e597070621ef6f927',
    messagingSenderId: '381990099686',
    projectId: 'carrier-6d7c1',
    storageBucket: 'carrier-6d7c1.firebasestorage.app',
    iosBundleId: 'com.example.carrier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7otd3nTN63ydPyIBR9BmT0jvZ2xkwO6w',
    appId: '1:381990099686:ios:3ed83e597070621ef6f927',
    messagingSenderId: '381990099686',
    projectId: 'carrier-6d7c1',
    storageBucket: 'carrier-6d7c1.firebasestorage.app',
    iosBundleId: 'com.example.carrier',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoATrZhVHaXK_pEXJjjxXVpNErJ536aHU',
    appId: '1:381990099686:web:052d0b76310edfd4f6f927',
    messagingSenderId: '381990099686',
    projectId: 'carrier-6d7c1',
    authDomain: 'carrier-6d7c1.firebaseapp.com',
    storageBucket: 'carrier-6d7c1.firebasestorage.app',
  );
}
